apiVersion: apps/v1   #接口版本
kind: Deployment                 #接口类型
metadata:
  name: goapp-deploy
  namespace: goapp-deploy
  labels:
    app: goappk8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goappk8s
  revisionHistoryLimit: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: goappk8s
    spec:
      containers:
        - image: goappk8s
          imagePullPolicy: Never
          name: goappk8s
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2