apiVersion: v1
kind: Service
metadata:
  namespace: goapp-deploy
  name: goapp-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 8080
      targetPort: 8080
  selector:
    app: goappk8s